### PR TITLE
Move docker-compose to top-level

### PR DESCRIPTION
**Pull request by hypesystem**
We only have the one file in the docker-compose folder, so there seems to be no reason to keep the file in there.

### CODE REVIEW

**Review by hypesystem — COMMENTED** [review]
✅

**Comment by ath88** [comment]
My previous comment on this was that we probably rather soon need a
docker-compose-specific configuration file, which conveniently could be out
inside the docker-compose directory. :)

It seems a few people has been annoyed with the current configuration
monster.

**Comment by hypesystem** [comment]
We agreed that we would wait and see until our big refactoring was done -- and it is now -- and move it out if no need existed. We can always create a folder again if we need it in the future :smile:

**Comment by ath88** [comment]
Sure thing. Just wanted to highlight the reasons for the initial directory.
:)

**Pull request merged**
