### PR TITLE
Add wait-for-it.sh script

### PR DESCRIPTION
**Pull request by ath88**

### CODE REVIEW

**Review by Arth101 — APPROVED** [review]

**Comment by hypesystem** [comment]
All I want for christmas is a better way to depend on wait-for-it.sh scripts across packages so we don't have to just copy the sh script code into places. I want versioning, I want changelogs, I want it all

**Comment by ath88** [comment]
Git sub repos?

**Comment by hypesystem** [comment]
I was thinking more along the lines of a package that could be installed somehow... if we could make wait-for-it a npm package, we can execute it with `npx` where needed (potentially installing as dev dependency, too)?

**Comment by ath88** [comment]
The problem is that it must be runnable from inside the containers, which
might not be running nodejs at all. Also - I think it would be dirty to
include it into the docker image, considering that it could just be a part
of the docker-compose setup.

The necessity of such docker-compose-related files was my reasoning behind
having a docker-compose-directory in the first place.

The ideal solution - in my view - would be if docker-compose itself had a
more mature readiness-concept.

**Comment by hypesystem** [comment]
I'm not saying it should be part of a docker image. I'm also not saying that the npm solution will work for everything, but for a lot of cases it will.

My suggestion is to support something like this:

1. `npm i wait-for-it`
2. Add volume `${PWD}/node_modules/.bin/wait-for-it.sh:/wait-for-it.sh` (notice wait-for-it is a binary in node_modules)
3. Add the same command you have added, e.g. `/wait-for-it.sh elasticsearch:9200 -- npm run install-and-start`

On machines that run npm we could make sure to install dev dependencies, which meas we would not need to mount in the volume and could run `npx wait-for-it` instead :smile:

**Pull request merged**
